[workspace]
resolver = "2"
members = [
    "crates/car-reader",
    "crates/blockzilla-format",
    "crates/optimize-car-archive",
    "blockzilla",
]
exclude = ["solana-prog/"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/ferno-ag/blockzilla"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = false
debug = false
incremental = false
overflow-checks = false

[profile.release-debug]
inherits = "release"
debug = true