[package]
name = "blockzilla"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
cid = "0.11"
multihash = "0.19.3"
multihash-codetable = {version="0.1.4", features = ["sha1", "sha2", "sha3", "ripemd", "strobe", "blake2b", "blake2s", "blake3"]}
serde = { version = "1", features = ["derive"] }
anyhow = "1"
futures = "0.3"
futures-util = "0.3"
clap = { version = "4.5.48", features = ["derive"] }
tokio = { version = "1.47", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat", "io"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "time"] }
prost = "0.14.1"
prost-types = "0.14.1"
base64 = "0.22.1"
solana-transaction-status-client-types = "3.0.5"
solana-reward-info = "3.0.0"
solana-transaction-error = "3.0.0"
solana-account-decoder-client-types = "3.0.5"
ahash = { version = "0.8.12", features = ["serde"] }
smallvec = "1.15.1"
solana-message = { version = "3.0.1", features = ["bincode"] }
solana-instruction = { version = "3.0.0", features = ["bincode"] }
minicbor = { version = "2.1.1", features = ["full"] }
wincode = { version = "0.1.1", features = ["derive", "solana-short-vec"] }
indicatif = { version = "0.18", features = ["futures"] }
mimalloc = "0.1.48"
once_cell = "1.21.3"
bytes = "1.10.1"
solana-pubkey = "3.0.0"
reqwest = { version = "0.12", features = ["stream", "gzip", "brotli", "deflate", "rustls-tls"] }
tokio-stream = "0.1"
dashmap = { version = "6.1.0", features = ["serde"] }
rand = "0.9.2"
which = "8.0.0"
sled = "0.34.7"
serde_json = "1.0.145"
fxhash = "0.2.1"
rayon = "1.11.0"
zstd = "0.13.3"
solana-signature = "3.1.0"
memmap2 = "0.9.9"
bs58 = "0.5"
postcard = { version = "1.0", features = ["use-std"] }

[build-dependencies]
prost-build = "0.14.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = false
debug = false
incremental = false
overflow-checks = false
