[package]
name = "blockzilla"
version = "0.1.0"
edition = "2024"

[dependencies]
humantime = "2.1"
cid = "0.11"
multihash = "0.19.3"
multihash-codetable = {version="0.1.4", features = ["sha1", "sha2", "sha3", "ripemd", "strobe", "blake2b", "blake2s", "blake3"]}
serde = { version = "1", features = ["derive"] }
minicbor = { version = "0.25", features = ["std"] }
anyhow = "1"
futures = "0.3"
futures-util = "0.3"
clap = { version = "4.5.48", features = ["derive"] }
tokio = { version = "1.47", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat", "io"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "time"] }
solana-storage-proto = "3.0.5"
prost = { version="0.11.9" }
prost-types = "0.11.9"
base64 = "0.22.1"
solana-sdk = "3.0.0"
bincode = "1.3.3"
zstd = "0.13.3"
serde_json = "1.0.145"
solana-transaction-status-client-types = "3.0.5"
base58 = "0.2.0"
solana-reward-info = "3.0.0"
solana-transaction-error = "3.0.0"
solana-account-decoder-client-types = "3.0.5"
rusqlite = "0.37.0"
postcard = { version = "1.1.3", features = ["alloc"] }
reqwest = { version = "0.12", default-features = false, features = ["stream", "rustls-tls"] }
dashmap = "5"
rayon = "1.10"
crossbeam-channel = "0.5"
arc-swap = "1.7"
serde_cbor = "0.11.2"

[profile.release]
opt-level = 3
lto = "fat"                # full link-time optimization across crates
codegen-units = 1          # compile slower, but optimize globally
panic = "abort"            # smaller binary, no stack unwinding
strip = true               # strip debug symbols
debug = false
incremental = false
overflow-checks = false
