[package]
name = "car-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bytes = "1"
cid = "0.11"
minicbor = { version = "2.1", features = ["alloc", "derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
