[package]
name = "blockzilla"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "blockzilla"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
blockzilla-format = { path = "../crates/blockzilla-format" }
prost = "0.14"
zstd = "0.13.3"
serde = "1.0.228"
anyhow = "1.0.100"
postcard = "1.1.3"
