[package]
name = "compact-archive"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
wincode = { version = "0.2.1", features = ["derive", "solana-short-vec"] }
postcard = { version = "1.0", features = ["use-std"] }
